### ISSUE TITLE
Hi , Can u also add a cheat sheet where u can tell us about the commands for togglinn neo tree etc.

### ISSUE THREAD

**Issue by reactVishnu** [magidc/nvim-config#6]

**Comment by magidc** [comment]
Hi, thats not a bad idea. I will added soon, thanks!
Anyway, I would like to explain something about the current commands. All of key combinations from this configuration are defined in the [mappings.lua](https://github.com/magidc/nvim-config/blob/master/lua/mappings.lua). The file is documented with the description of each command.
Most commands have the format leader + category + command. Leader is currently set to space, categories include "views", "find, "refactor", "source", "debug". etc. Everything is based in mnemonic principles that make it easier to remember, for example, if you wanna view the file tree (Neotree), just type " " + "v"(Views) + "f" (Files).
If you wanna change the name of a variable type " " + "r"(refactor)+"n"(name). If you wanna find by name " " + "f"(find) + "n"(name)...
However there are exceptions in this mnenomic approach. The reason is to make easier those actions that are most common. For example to find files " " + "f"(find) + "e". Why "e", because "e" is placed close to "f" in qwerty keyboards so is easier to tap. The most commonly use commands follow this principle. The last letter is next to  the previous one, I found this just convenient.

My config includes WhichKey plugin that it helps you learning the commands. When you type for example " " + v, it automatically show you the commands you can use in the "View" category with their descriptions:
![image](https://github.com/magidc/nvim-config/assets/4416693/46ac2518-3013-4310-a30e-699aee8e892b)
This is for "Find" category commands (" " + "f"):
![image](https://github.com/magidc/nvim-config/assets/4416693/1158ea22-15f5-411d-ae1e-c0f71a731a60)

If you wanna see all possible commands from the beginning, just call :WhichKey.

I hope this helps!
